In [ ]:
import numpy as np
import random

In [ ]:
def rec_err(w, H, B):
    """
    Функция поиска и определения ошибки в сообщении.

    Args:
        w: Полученное сообщение с потенциальной ошибкой.
        H: Проверочная матрица.
        B: Матрица для расширения кода.

    Returns:
        Ошибка, если она была найдена, иначе None.
    """
    s = w @ H % 2
    if sum(s) <= 3:
        return np.hstack((s, np.zeros(len(s), dtype=int)))
    sB = s @ B % 2
    if sum(sB) <= 3:
        return np.hstack((np.zeros(len(s), dtype=int), sB))
    for i in range(len(B)):
        temp = (sB + B[i]) % 2
        if sum(temp) <= 2:
            ei = np.zeros(len(s), dtype=int)
            ei[i] = 1
            return np.hstack((ei, temp))
    return None

In [ ]:
def create_and_control_err(u, G, H, B, error_rate):
    """
    Функция для имитации ошибки и проверки ее исправления.

    Args:
        u: Исходное сообщение.
        G: Порождающая матрица.
        H: Проверочная матрица.
        B: Матрица для расширения кода.
        error_rate: Количество ошибок, которые нужно добавить.
    """
    print("Исходное сообщение:", u)
    w = u @ G % 2
    print("Отправленное сообщение", w)
    error = np.zeros(w.shape[0], dtype=int)
    error_indices = random.sample(range(w.shape[0]), error_rate)
    for index in error_indices:
        error[index] = 1
    print("Допущенная ошибка:", error)
    w = (w + error) % 2
    print("Сообщение с ошибкой", w)
    error = rec_err(w, H, B)
    print("Вызовем get_error, получаем ошибку:", error)
    if error is None:
        print("Ошибка обнаружена, исправить невозможно!")
        return
    message = (w + error) % 2
    print("Исправленное отправленное сообщение:", message)
    w = u @ G % 2
    if not np.array_equal(w, message):
        print("Сообщение было декодировано с ошибкой!")

In [ ]:
def read_muller_gen_matrix(r: int, m: int) -> np.ndarray:
    """
    Генерация матрицы кода Рида-Мюллера.

    Args:
        r: Порядок кода.
        m: Количество информационных бит.

    Returns:
        Матрица кода Рида-Мюллера.
    """
    if r == 0:
        return np.ones((1, 2 ** m), dtype=int)
    if r == m:
        G_m_m_1_m = read_muller_gen_matrix(m - 1, m)
        bottom_row = np.zeros((1, 2 ** m), dtype=int)
        bottom_row[0, -1] = 1
        return np.vstack([G_m_m_1_m, bottom_row])
    G_r_m_m_1 = read_muller_gen_matrix(r, m - 1)
    G_r_m_1_m_m_1 = read_muller_gen_matrix(r - 1, m - 1)
    top = np.hstack([G_r_m_m_1, G_r_m_m_1])
    bottom = np.hstack([np.zeros((G_r_m_1_m_m_1.shape[0], G_r_m_1_m_m_1.shape[1]), dtype=int), G_r_m_1_m_m_1])
    return np.vstack([top, bottom])

In [ ]:
    print("Задаем матрицу B для расширенного кода Голея")
    B = np.array([[1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
                  [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
                  [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
                  [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
                  [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
                  [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
                  [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
                  [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
                  [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
                  [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
                  [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
                  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])
    print(B)

Задаем матрицу B для расширенного кода Голея
[[1 1 0 1 1 1 0 0 0 1 0 1]
 [1 0 1 1 1 0 0 0 1 0 1 1]
 [0 1 1 1 0 0 0 1 0 1 1 1]
 [1 1 1 0 0 0 1 0 1 1 0 1]
 [1 1 0 0 0 1 0 1 1 0 1 1]
 [1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 1 0 1 1 0 1 1 1 0 1]
 [0 1 0 1 1 0 1 1 1 0 0 1]
 [1 0 1 1 0 1 1 1 0 0 0 1]
 [0 1 1 0 1 1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0]]


In [ ]:
print("\nСтроим порождающую матрицу")
G = np.hstack((np.eye(12, 12, dtype=int), B))
print(G)


Строим порождающую матрицу
[[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]]


In [ ]:
print("\nСтроим проверочную матрицу")
H = np.vstack((np.eye(12, 12, dtype=int), B))
print(H)


Строим проверочную матрицу
[[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 0 0 1 0 1]
 [1 0 1 1 1 0 0 0 1 0 1 1]
 [0 1 1 1 0 0 0 1 0 1 1 1]
 [1 1 1 0 0 0 1 0 1 1 0 1]
 [1 1 0 0 0 1 0 1 1 0 1 1]
 [1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 1 0 1 1 0 1 1 1 0 1]
 [0 1 0 1 1 0 1 1 1 0 0 1]
 [1 0 1 1 0 1 1 1 0 0 0 1]
 [0 1 1 0 1 1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0]]


In [ ]:
print("Отправляем сообщение (1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0). Допустим однократную ошибку\n")
u = np.array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0])
create_and_control_err(u, G, H, B, 1)

Отправляем сообщение (1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0). Допустим однократную ошибку

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Допущенная ошибка: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Сообщение с ошибкой [1 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Вызовем get_error, получаем ошибку: [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


In [ ]:
print("\nДопустим двухкратную ошибку\n")
create_and_control_err(u, G, H, B, 2)


Допустим двухкратную ошибку

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Допущенная ошибка: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
Сообщение с ошибкой [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 0 0 1 1]
Вызовем get_error, получаем ошибку: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


In [ ]:
print("\nДопустим трехкратную ошибку\n")
create_and_control_err(u, G, H, B, 3)


Допустим трехкратную ошибку

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Допущенная ошибка: [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
Сообщение с ошибкой [1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 1 0]
Вызовем get_error, получаем ошибку: [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


In [ ]:
print("\nДопустим четырехкратную ошибку\n")
create_and_control_err(u, G, H, B, 4)


Допустим четырехкратную ошибку

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Допущенная ошибка: [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0]
Сообщение с ошибкой [1 0 0 1 1 0 0 0 1 0 1 1 1 1 1 0 1 1 1 0 0 0 1 1]
Вызовем get_error, получаем ошибку: None
Ошибка обнаружена, исправить невозможно!


In [ ]:
print("Введена функция для формирования порождающей матрицы кода Рида-Маллера\n")
print("Сформируем порождающую матрицу для RM(1, 3)")
G = read_muller_gen_matrix(1, 3)
print(G)

Введена функция для формирования порождающей матрицы кода Рида-Маллера

Сформируем порождающую матрицу для RM(1, 3)
[[1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]]


In [ ]:
def kronecker_product(A: np.ndarray, B: np.ndarray) -> np.ndarray:
  """
  Вычисляет произведение Кронекера двух матриц.

  Args:
    A: Первая матрица.
    B: Вторая матрица.

  Returns:
    Произведение Кронекера матриц A и B.
  """
  # Получаем размеры матриц
  rows_A, cols_A = A.shape
  rows_B, cols_B = B.shape

  # Инициализируем результирующую матрицу
  result = np.zeros((rows_A * rows_B, cols_A * cols_B), dtype=A.dtype)

  # Вычисляем произведение Кронекера
  for i in range(rows_A):
    for j in range(cols_A):
      result[i*rows_B:(i+1)*rows_B, j*cols_B:(j+1)*cols_B] = A[i, j] * B

  return result

In [ ]:
def H_matrix(H: np.ndarray, m: int, i: int) -> np.ndarray:
  """
  Формирует матрицу H для проверки кода Рида-Маллера.

  Args:
    H: Матрица проверки для кода Рида-Маллера.
    m: Количество информационных бит.
    i: Индекс для формирования матрицы H.

  Returns:
    Матрица H для проверки кода Рида-Маллера.
  """
  matrix = np.eye(2**(m - i), dtype=int)
  matrix = kronecker_product(matrix, H)
  matrix = kronecker_product(matrix, np.eye(2**(i - 1)))
  return matrix

In [ ]:
def gen_and_check_error_RM(u: np.ndarray, G: np.ndarray, error_rate: int, m: int):
  """
  Генерирует кодовое слово, добавляет ошибки и пытается исправить их.

  Args:
    u: Исходное сообщение.
    G: Порождающая матрица кода Рида-Маллера.
    error_rate: Количество ошибок, добавляемых в кодовое слово.
    m: Количество информационных бит.
  """
  print("Исходное сообщение:", u)
  w = u @ G % 2
  print("Отправленное сообщение", w)
  error = np.zeros(w.shape[0], dtype=int)
  error_indices = random.sample(range(w.shape[0]), error_rate)
  for index in error_indices:
    error[index] = 1
  print("Допущенная ошибка:", error)
  w = (w + error) % 2
  print("Сообщение с ошибкой", w)
  for i in range(len(w)):
    if w[i] == 0:
      w[i] = -1
  w_array = []
  H = np.array([[1, 1], [1, -1]])
  w_array.append(w @ H_matrix(H, m, 1))
  for i in range(2, m + 1):
    w_array.append(w_array[-1] @ H_matrix(H, m, i))
  maximum = w_array[0][0]
  index = -1
  for i in range(len(w_array)):
    for j in range(len(w_array[i])):
      if abs(w_array[i][j]) > abs(maximum):
        index = j
        maximum = w_array[i][j]
  counter = 0
  for i in range(len(w_array)):
    for j in range(len(w_array[i])):
      if abs(w_array[i][j]) == abs(maximum):
        counter += 1
      if (counter > 1):
        print("Невозможно исправить ошибку!")
        return
  message = list(map(int, list(('{' + f'0:0{m}b' + '}').format(index))))
  if maximum > 0:
    message.append(1)
  else:
    message.append(0)
  print("Исправленное сообщение:", np.array(message[::-1]))
  if (not np.array_equal(u, message)):
    print("Сообщение было декодировано с ошибкой!")


In [ ]:
# Допустим однократную ошибку
m = 3
u = np.array([1, 0, 0, 1])
G = read_muller_gen_matrix(1, 3)
gen_and_check_error_RM(u, G, 1, m)




Исходное сообщение: [1 0 0 1]
Отправленное сообщение [1 1 1 1 0 0 0 0]
Допущенная ошибка: [0 1 0 0 0 0 0 0]
Сообщение с ошибкой [1 0 1 1 0 0 0 0]
Исправленное сообщение: [1 0 0 1]


In [ ]:
# Допустим двухкратную ошибку
gen_and_check_error_RM(u, G, 2, m)




Исходное сообщение: [1 0 0 1]
Отправленное сообщение [1 1 1 1 0 0 0 0]
Допущенная ошибка: [1 0 1 0 0 0 0 0]
Сообщение с ошибкой [0 1 0 1 0 0 0 0]
Невозможно исправить ошибку!


In [ ]:
# Сформируем порождающую матрицу для RM(1, 4)
G = read_muller_gen_matrix(1, 4)
print(G)



[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]


In [ ]:
# Допустим однократную ошибку
m = 4
u = np.array([1, 0, 1, 0, 1])
gen_and_check_error_RM(u, G, 1, m)



Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
Сообщение с ошибкой [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 0]
Исправленное сообщение: [1 0 1 0 1]


In [ ]:
# Допустим двухкратную ошибку
gen_and_check_error_RM(u, G, 2, m)



Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0]
Сообщение с ошибкой [1 1 0 0 1 1 0 1 0 0 1 1 1 0 1 1]
Исправленное сообщение: [1 0 1 0 1]


In [ ]:
# Допустим трехкратную ошибку
gen_and_check_error_RM(u, G, 3, m)


Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0]
Сообщение с ошибкой [1 1 0 1 1 1 0 1 0 0 1 0 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]


In [ ]:
# Допустим четырехкратную ошибку
gen_and_check_error_RM(u, G, 4, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0]
Сообщение с ошибкой [1 1 0 1 1 0 0 0 1 0 1 1 1 0 1 1]
Невозможно исправить ошибку!
